/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.equivalencia.telas;

/**
 *
 * @author ltrindade
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnArea = new javax.swing.JButton();
        btncurso = new javax.swing.JButton();
        btnGrupoEquiv = new javax.swing.JButton();
        btnuUnidades = new javax.swing.JButton();
        btnPpc = new javax.swing.JButton();
        btnEquivalencia = new javax.swing.JButton();
        menPrincipal = new javax.swing.JMenuBar();
        menCad = new javax.swing.JMenu();
        menCadarea_tecnologica = new javax.swing.JMenuItem();
        menCadcursos = new javax.swing.JMenu();
        menCadpcc = new javax.swing.JMenu();
        menCadGrupo = new javax.swing.JMenu();
        menCadUnidade = new javax.swing.JMenu();
        menCadUsuario = new javax.swing.JMenu();
        menEquiv = new javax.swing.JMenu();
        menEquivalencia = new javax.swing.JMenuItem();
        menAjuda = new javax.swing.JMenu();
        menFluxo = new javax.swing.JMenuItem();
        menManual = new javax.swing.JMenuItem();
        menLogout = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        menSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIS EQUIVALENCIA - SENAI VITORIA PRINCIPAL");

        btnArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/1249981_communication_linkedin_network_online_profession_icon.png"))); // NOI18N
        btnArea.setText("jButton1");
        btnArea.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/1249981_communication_linkedin_network_online_profession_icon.png"))); // NOI18N

        btncurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/4212905_education_graduation_mouse_online_icon.png"))); // NOI18N
        btncurso.setText("jButton2");

        btnGrupoEquiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/5027884_document_documents_file_format_paper_icon.png"))); // NOI18N
        btnGrupoEquiv.setText("jButton3");

        btnuUnidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/6643377_balance_diet_fitness_protein_vegetable_icon.png"))); // NOI18N
        btnuUnidades.setText("jButton4");

        btnPpc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/6971758_ui_bassic_device_units_unit_icon.png"))); // NOI18N
        btnPpc.setText("jButton5");

        btnEquivalencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/7465087_scale_balance_tool_icon.png"))); // NOI18N
        btnEquivalencia.setText("jButton6");

        menCad.setText("cadastro");
        menCad.setEnabled(false);

        menCadarea_tecnologica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/7465087_scale_balance_tool_icon_1.png"))); // NOI18N
        menCadarea_tecnologica.setText("area tecnologica");
        menCad.add(menCadarea_tecnologica);

        menCadcursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/7465087_scale_balance_tool_icon_1.png"))); // NOI18N
        menCadcursos.setText("cursos");
        menCad.add(menCadcursos);

        menCadpcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/7465087_scale_balance_tool_icon_1.png"))); // NOI18N
        menCadpcc.setText("pcc");
        menCad.add(menCadpcc);

        menCadGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/7465087_scale_balance_tool_icon_1.png"))); // NOI18N
        menCadGrupo.setText("grupo de equivalencia");
        menCad.add(menCadGrupo);

        menCadUnidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/7465087_scale_balance_tool_icon_1.png"))); // NOI18N
        menCadUnidade.setText("unidade curricular ");
        menCad.add(menCadUnidade);

        menCadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/7465087_scale_balance_tool_icon_1.png"))); // NOI18N
        menCadUsuario.setText("usuario");
        menCad.add(menCadUsuario);

        menPrincipal.add(menCad);

        menEquiv.setText("equivalencia");

        menEquivalencia.setText("realizar equivalncia");
        menEquiv.add(menEquivalencia);

        menPrincipal.add(menEquiv);

        menAjuda.setText("ajuda");

        menFluxo.setText("fluxo de processo ");
        menAjuda.add(menFluxo);

        menManual.setText("manual");
        menAjuda.add(menManual);

        menPrincipal.add(menAjuda);

        menLogout.setText("opçoes");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem4.setText("logout  ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menLogout.add(jMenuItem4);

        menSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        menSair.setText("sair    ");
        menSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSairActionPerformed(evt);
            }
        });
        menLogout.add(menSair);

        menPrincipal.add(menLogout);

        setJMenuBar(menPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnuUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArea, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btncurso, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPpc, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGrupoEquiv, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(815, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArea, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncurso, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrupoEquiv, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnuUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPpc, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(438, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menSairActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        TELALogin login = new TELALogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArea;
    private javax.swing.JButton btnEquivalencia;
    private javax.swing.JButton btnGrupoEquiv;
    private javax.swing.JButton btnPpc;
    private javax.swing.JButton btncurso;
    private javax.swing.JButton btnuUnidades;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu menAjuda;
    public static javax.swing.JMenu menCad;
    private javax.swing.JMenu menCadGrupo;
    private javax.swing.JMenu menCadUnidade;
    private javax.swing.JMenu menCadUsuario;
    private javax.swing.JMenuItem menCadarea_tecnologica;
    private javax.swing.JMenu menCadcursos;
    private javax.swing.JMenu menCadpcc;
    private javax.swing.JMenu menEquiv;
    private javax.swing.JMenuItem menEquivalencia;
    private javax.swing.JMenuItem menFluxo;
    private javax.swing.JMenu menLogout;
    private javax.swing.JMenuItem menManual;
    private javax.swing.JMenuBar menPrincipal;
    private javax.swing.JMenuItem menSair;
    // End of variables declaration//GEN-END:variables
}
